// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions
} from '@tanstack/react-query'
import type { AxiosError } from 'axios'

import { client } from '../client.gen'
import {
  acceptDecisionApiV1CurationDecisionsDecisionIdAcceptPost,
  assignDecisionApiV1CurationDecisionsDecisionIdAssignPost,
  bulkAcceptDecisionsApiV1CurationDecisionsBulkAcceptPost,
  bulkRejectDecisionsApiV1CurationDecisionsBulkRejectPost,
  createUserApiV1UsersPost,
  getAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGet,
  getCurrentUserApiV1UsersMeGet,
  getProposedCanonicalEntityApiV1CurationDecisionsDecisionIdProposedCanonicalEntityGet,
  getStatisticsApiV1CurationStatsGet,
  healthHealthGet,
  listDecisionsApiV1CurationDecisionsGet,
  listUserActionsApiV1UserActionsGet,
  listUsersApiV1UsersGet,
  loginApiV1AuthLoginPost,
  type Options,
  patchUserApiV1UsersUserIdPatch,
  refreshApiV1AuthRefreshPost,
  registerApiV1AuthRegisterPost,
  rejectDecisionApiV1CurationDecisionsDecisionIdRejectPost
} from '../sdk.gen'
import type {
  AcceptDecisionApiV1CurationDecisionsDecisionIdAcceptPostData,
  AcceptDecisionApiV1CurationDecisionsDecisionIdAcceptPostError,
  AcceptDecisionApiV1CurationDecisionsDecisionIdAcceptPostResponse,
  AssignDecisionApiV1CurationDecisionsDecisionIdAssignPostData,
  AssignDecisionApiV1CurationDecisionsDecisionIdAssignPostError,
  AssignDecisionApiV1CurationDecisionsDecisionIdAssignPostResponse,
  BulkAcceptDecisionsApiV1CurationDecisionsBulkAcceptPostData,
  BulkAcceptDecisionsApiV1CurationDecisionsBulkAcceptPostError,
  BulkAcceptDecisionsApiV1CurationDecisionsBulkAcceptPostResponse,
  BulkRejectDecisionsApiV1CurationDecisionsBulkRejectPostData,
  BulkRejectDecisionsApiV1CurationDecisionsBulkRejectPostError,
  BulkRejectDecisionsApiV1CurationDecisionsBulkRejectPostResponse,
  CreateUserApiV1UsersPostData,
  CreateUserApiV1UsersPostError,
  CreateUserApiV1UsersPostResponse,
  GetAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGetData,
  GetAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGetError,
  GetAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGetResponse,
  GetCurrentUserApiV1UsersMeGetData,
  GetCurrentUserApiV1UsersMeGetError,
  GetCurrentUserApiV1UsersMeGetResponse,
  GetProposedCanonicalEntityApiV1CurationDecisionsDecisionIdProposedCanonicalEntityGetData,
  GetProposedCanonicalEntityApiV1CurationDecisionsDecisionIdProposedCanonicalEntityGetError,
  GetProposedCanonicalEntityApiV1CurationDecisionsDecisionIdProposedCanonicalEntityGetResponse,
  GetStatisticsApiV1CurationStatsGetData,
  GetStatisticsApiV1CurationStatsGetError,
  GetStatisticsApiV1CurationStatsGetResponse,
  HealthHealthGetData,
  HealthHealthGetResponse,
  ListDecisionsApiV1CurationDecisionsGetData,
  ListDecisionsApiV1CurationDecisionsGetError,
  ListDecisionsApiV1CurationDecisionsGetResponse,
  ListUserActionsApiV1UserActionsGetData,
  ListUserActionsApiV1UserActionsGetError,
  ListUserActionsApiV1UserActionsGetResponse,
  ListUsersApiV1UsersGetData,
  ListUsersApiV1UsersGetError,
  ListUsersApiV1UsersGetResponse,
  LoginApiV1AuthLoginPostData,
  LoginApiV1AuthLoginPostError,
  LoginApiV1AuthLoginPostResponse,
  PatchUserApiV1UsersUserIdPatchData,
  PatchUserApiV1UsersUserIdPatchError,
  PatchUserApiV1UsersUserIdPatchResponse,
  RefreshApiV1AuthRefreshPostData,
  RefreshApiV1AuthRefreshPostError,
  RefreshApiV1AuthRefreshPostResponse,
  RegisterApiV1AuthRegisterPostData,
  RegisterApiV1AuthRegisterPostError,
  RegisterApiV1AuthRegisterPostResponse,
  RejectDecisionApiV1CurationDecisionsDecisionIdRejectPostData,
  RejectDecisionApiV1CurationDecisionsDecisionIdRejectPostError,
  RejectDecisionApiV1CurationDecisionsDecisionIdRejectPostResponse
} from '../types.gen'

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string
    _infinite?: boolean
    tags?: ReadonlyArray<string>
  }
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (tags) {
    params.tags = tags
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

export const healthHealthGetQueryKey = (
  options?: Options<HealthHealthGetData>
) => createQueryKey('healthHealthGet', options)

/**
 * Health
 *
 * Health check endpoint to verify the service is running.
 */
export const healthHealthGetOptions = (
  options?: Options<HealthHealthGetData>
) =>
  queryOptions<
    HealthHealthGetResponse,
    AxiosError<DefaultError>,
    HealthHealthGetResponse,
    ReturnType<typeof healthHealthGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await healthHealthGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: healthHealthGetQueryKey(options)
  })

/**
 * Register
 *
 * Register a new user account.
 */
export const registerApiV1AuthRegisterPostMutation = (
  options?: Partial<Options<RegisterApiV1AuthRegisterPostData>>
): UseMutationOptions<
  RegisterApiV1AuthRegisterPostResponse,
  AxiosError<RegisterApiV1AuthRegisterPostError>,
  Options<RegisterApiV1AuthRegisterPostData>
> => {
  const mutationOptions: UseMutationOptions<
    RegisterApiV1AuthRegisterPostResponse,
    AxiosError<RegisterApiV1AuthRegisterPostError>,
    Options<RegisterApiV1AuthRegisterPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await registerApiV1AuthRegisterPost({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

/**
 * Login
 *
 * Authenticate and receive access + refresh tokens.
 */
export const loginApiV1AuthLoginPostMutation = (
  options?: Partial<Options<LoginApiV1AuthLoginPostData>>
): UseMutationOptions<
  LoginApiV1AuthLoginPostResponse,
  AxiosError<LoginApiV1AuthLoginPostError>,
  Options<LoginApiV1AuthLoginPostData>
> => {
  const mutationOptions: UseMutationOptions<
    LoginApiV1AuthLoginPostResponse,
    AxiosError<LoginApiV1AuthLoginPostError>,
    Options<LoginApiV1AuthLoginPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await loginApiV1AuthLoginPost({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

/**
 * Refresh
 *
 * Exchange a refresh token for a new token pair.
 */
export const refreshApiV1AuthRefreshPostMutation = (
  options?: Partial<Options<RefreshApiV1AuthRefreshPostData>>
): UseMutationOptions<
  RefreshApiV1AuthRefreshPostResponse,
  AxiosError<RefreshApiV1AuthRefreshPostError>,
  Options<RefreshApiV1AuthRefreshPostData>
> => {
  const mutationOptions: UseMutationOptions<
    RefreshApiV1AuthRefreshPostResponse,
    AxiosError<RefreshApiV1AuthRefreshPostError>,
    Options<RefreshApiV1AuthRefreshPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await refreshApiV1AuthRefreshPost({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

export const listDecisionsApiV1CurationDecisionsGetQueryKey = (
  options?: Options<ListDecisionsApiV1CurationDecisionsGetData>
) => createQueryKey('listDecisionsApiV1CurationDecisionsGet', options)

/**
 * List Decisions
 *
 * Retrieve cursor-paginated list of decisions with optional filtering.
 */
export const listDecisionsApiV1CurationDecisionsGetOptions = (
  options?: Options<ListDecisionsApiV1CurationDecisionsGetData>
) =>
  queryOptions<
    ListDecisionsApiV1CurationDecisionsGetResponse,
    AxiosError<ListDecisionsApiV1CurationDecisionsGetError>,
    ListDecisionsApiV1CurationDecisionsGetResponse,
    ReturnType<typeof listDecisionsApiV1CurationDecisionsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listDecisionsApiV1CurationDecisionsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: listDecisionsApiV1CurationDecisionsGetQueryKey(options)
  })

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>
>(
  queryKey: QueryKey<Options>,
  page: K
) => {
  const params = { ...queryKey[0] }
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any)
    }
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers
    }
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any)
    }
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any)
    }
  }
  return params as unknown as typeof page
}

export const listDecisionsApiV1CurationDecisionsGetInfiniteQueryKey = (
  options?: Options<ListDecisionsApiV1CurationDecisionsGetData>
): QueryKey<Options<ListDecisionsApiV1CurationDecisionsGetData>> =>
  createQueryKey('listDecisionsApiV1CurationDecisionsGet', options, true)

/**
 * List Decisions
 *
 * Retrieve cursor-paginated list of decisions with optional filtering.
 */
export const listDecisionsApiV1CurationDecisionsGetInfiniteOptions = (
  options?: Options<ListDecisionsApiV1CurationDecisionsGetData>
) =>
  infiniteQueryOptions<
    ListDecisionsApiV1CurationDecisionsGetResponse,
    AxiosError<ListDecisionsApiV1CurationDecisionsGetError>,
    InfiniteData<ListDecisionsApiV1CurationDecisionsGetResponse>,
    QueryKey<Options<ListDecisionsApiV1CurationDecisionsGetData>>,
    | string
    | null
    | Pick<
        QueryKey<Options<ListDecisionsApiV1CurationDecisionsGetData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListDecisionsApiV1CurationDecisionsGetData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  cursor: pageParam
                }
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await listDecisionsApiV1CurationDecisionsGet({
          ...options,
          ...params,
          signal,
          throwOnError: true
        })
        return data
      },
      queryKey: listDecisionsApiV1CurationDecisionsGetInfiniteQueryKey(options)
    }
  )

export const getProposedCanonicalEntityApiV1CurationDecisionsDecisionIdProposedCanonicalEntityGetQueryKey =
  (
    options: Options<GetProposedCanonicalEntityApiV1CurationDecisionsDecisionIdProposedCanonicalEntityGetData>
  ) =>
    createQueryKey(
      'getProposedCanonicalEntityApiV1CurationDecisionsDecisionIdProposedCanonicalEntityGet',
      options
    )

/**
 * Get Proposed Canonical Entity
 *
 * Get the proposed canonical entity for a given decision.
 */
export const getProposedCanonicalEntityApiV1CurationDecisionsDecisionIdProposedCanonicalEntityGetOptions =
  (
    options: Options<GetProposedCanonicalEntityApiV1CurationDecisionsDecisionIdProposedCanonicalEntityGetData>
  ) =>
    queryOptions<
      GetProposedCanonicalEntityApiV1CurationDecisionsDecisionIdProposedCanonicalEntityGetResponse,
      AxiosError<GetProposedCanonicalEntityApiV1CurationDecisionsDecisionIdProposedCanonicalEntityGetError>,
      GetProposedCanonicalEntityApiV1CurationDecisionsDecisionIdProposedCanonicalEntityGetResponse,
      ReturnType<
        typeof getProposedCanonicalEntityApiV1CurationDecisionsDecisionIdProposedCanonicalEntityGetQueryKey
      >
    >({
      queryFn: async ({ queryKey, signal }) => {
        const { data } =
          await getProposedCanonicalEntityApiV1CurationDecisionsDecisionIdProposedCanonicalEntityGet(
            {
              ...options,
              ...queryKey[0],
              signal,
              throwOnError: true
            }
          )
        return data
      },
      queryKey:
        getProposedCanonicalEntityApiV1CurationDecisionsDecisionIdProposedCanonicalEntityGetQueryKey(
          options
        )
    })

export const getAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGetQueryKey =
  (
    options: Options<GetAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGetData>
  ) =>
    createQueryKey(
      'getAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGet',
      options
    )

/**
 * Get Alternative Canonical Entities
 *
 * Get alternative canonical entities for a given decision.
 */
export const getAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGetOptions =
  (
    options: Options<GetAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGetData>
  ) =>
    queryOptions<
      GetAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGetResponse,
      AxiosError<GetAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGetError>,
      GetAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGetResponse,
      ReturnType<
        typeof getAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGetQueryKey
      >
    >({
      queryFn: async ({ queryKey, signal }) => {
        const { data } =
          await getAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGet(
            {
              ...options,
              ...queryKey[0],
              signal,
              throwOnError: true
            }
          )
        return data
      },
      queryKey:
        getAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGetQueryKey(
          options
        )
    })

export const getAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGetInfiniteQueryKey =
  (
    options: Options<GetAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGetData>
  ): QueryKey<
    Options<GetAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGetData>
  > =>
    createQueryKey(
      'getAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGet',
      options,
      true
    )

/**
 * Get Alternative Canonical Entities
 *
 * Get alternative canonical entities for a given decision.
 */
export const getAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGetInfiniteOptions =
  (
    options: Options<GetAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGetData>
  ) =>
    infiniteQueryOptions<
      GetAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGetResponse,
      AxiosError<GetAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGetError>,
      InfiniteData<GetAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGetResponse>,
      QueryKey<
        Options<GetAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGetData>
      >,
      | number
      | Pick<
          QueryKey<
            Options<GetAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGetData>
          >[0],
          'body' | 'headers' | 'path' | 'query'
        >
    >(
      // @ts-ignore
      {
        queryFn: async ({ pageParam, queryKey, signal }) => {
          // @ts-ignore
          const page: Pick<
            QueryKey<
              Options<GetAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGetData>
            >[0],
            'body' | 'headers' | 'path' | 'query'
          > =
            typeof pageParam === 'object'
              ? pageParam
              : {
                  query: {
                    page: pageParam
                  }
                }
          const params = createInfiniteParams(queryKey, page)
          const { data } =
            await getAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGet(
              {
                ...options,
                ...params,
                signal,
                throwOnError: true
              }
            )
          return data
        },
        queryKey:
          getAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGetInfiniteQueryKey(
            options
          )
      }
    )

/**
 * Accept Decision
 *
 * Accept the proposed canonical entity match.
 */
export const acceptDecisionApiV1CurationDecisionsDecisionIdAcceptPostMutation =
  (
    options?: Partial<
      Options<AcceptDecisionApiV1CurationDecisionsDecisionIdAcceptPostData>
    >
  ): UseMutationOptions<
    AcceptDecisionApiV1CurationDecisionsDecisionIdAcceptPostResponse,
    AxiosError<AcceptDecisionApiV1CurationDecisionsDecisionIdAcceptPostError>,
    Options<AcceptDecisionApiV1CurationDecisionsDecisionIdAcceptPostData>
  > => {
    const mutationOptions: UseMutationOptions<
      AcceptDecisionApiV1CurationDecisionsDecisionIdAcceptPostResponse,
      AxiosError<AcceptDecisionApiV1CurationDecisionsDecisionIdAcceptPostError>,
      Options<AcceptDecisionApiV1CurationDecisionsDecisionIdAcceptPostData>
    > = {
      mutationFn: async (fnOptions) => {
        const { data } =
          await acceptDecisionApiV1CurationDecisionsDecisionIdAcceptPost({
            ...options,
            ...fnOptions,
            throwOnError: true
          })
        return data
      }
    }
    return mutationOptions
  }

/**
 * Reject Decision
 *
 * Reject the proposed canonical entity match.
 */
export const rejectDecisionApiV1CurationDecisionsDecisionIdRejectPostMutation =
  (
    options?: Partial<
      Options<RejectDecisionApiV1CurationDecisionsDecisionIdRejectPostData>
    >
  ): UseMutationOptions<
    RejectDecisionApiV1CurationDecisionsDecisionIdRejectPostResponse,
    AxiosError<RejectDecisionApiV1CurationDecisionsDecisionIdRejectPostError>,
    Options<RejectDecisionApiV1CurationDecisionsDecisionIdRejectPostData>
  > => {
    const mutationOptions: UseMutationOptions<
      RejectDecisionApiV1CurationDecisionsDecisionIdRejectPostResponse,
      AxiosError<RejectDecisionApiV1CurationDecisionsDecisionIdRejectPostError>,
      Options<RejectDecisionApiV1CurationDecisionsDecisionIdRejectPostData>
    > = {
      mutationFn: async (fnOptions) => {
        const { data } =
          await rejectDecisionApiV1CurationDecisionsDecisionIdRejectPost({
            ...options,
            ...fnOptions,
            throwOnError: true
          })
        return data
      }
    }
    return mutationOptions
  }

/**
 * Assign Decision
 *
 * Assign the subject entity mention to a specific cluster.
 */
export const assignDecisionApiV1CurationDecisionsDecisionIdAssignPostMutation =
  (
    options?: Partial<
      Options<AssignDecisionApiV1CurationDecisionsDecisionIdAssignPostData>
    >
  ): UseMutationOptions<
    AssignDecisionApiV1CurationDecisionsDecisionIdAssignPostResponse,
    AxiosError<AssignDecisionApiV1CurationDecisionsDecisionIdAssignPostError>,
    Options<AssignDecisionApiV1CurationDecisionsDecisionIdAssignPostData>
  > => {
    const mutationOptions: UseMutationOptions<
      AssignDecisionApiV1CurationDecisionsDecisionIdAssignPostResponse,
      AxiosError<AssignDecisionApiV1CurationDecisionsDecisionIdAssignPostError>,
      Options<AssignDecisionApiV1CurationDecisionsDecisionIdAssignPostData>
    > = {
      mutationFn: async (fnOptions) => {
        const { data } =
          await assignDecisionApiV1CurationDecisionsDecisionIdAssignPost({
            ...options,
            ...fnOptions,
            throwOnError: true
          })
        return data
      }
    }
    return mutationOptions
  }

/**
 * Bulk Accept Decisions
 *
 * Accept multiple decisions in a single request.
 */
export const bulkAcceptDecisionsApiV1CurationDecisionsBulkAcceptPostMutation = (
  options?: Partial<
    Options<BulkAcceptDecisionsApiV1CurationDecisionsBulkAcceptPostData>
  >
): UseMutationOptions<
  BulkAcceptDecisionsApiV1CurationDecisionsBulkAcceptPostResponse,
  AxiosError<BulkAcceptDecisionsApiV1CurationDecisionsBulkAcceptPostError>,
  Options<BulkAcceptDecisionsApiV1CurationDecisionsBulkAcceptPostData>
> => {
  const mutationOptions: UseMutationOptions<
    BulkAcceptDecisionsApiV1CurationDecisionsBulkAcceptPostResponse,
    AxiosError<BulkAcceptDecisionsApiV1CurationDecisionsBulkAcceptPostError>,
    Options<BulkAcceptDecisionsApiV1CurationDecisionsBulkAcceptPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } =
        await bulkAcceptDecisionsApiV1CurationDecisionsBulkAcceptPost({
          ...options,
          ...fnOptions,
          throwOnError: true
        })
      return data
    }
  }
  return mutationOptions
}

/**
 * Bulk Reject Decisions
 *
 * Reject multiple decisions in a single request.
 */
export const bulkRejectDecisionsApiV1CurationDecisionsBulkRejectPostMutation = (
  options?: Partial<
    Options<BulkRejectDecisionsApiV1CurationDecisionsBulkRejectPostData>
  >
): UseMutationOptions<
  BulkRejectDecisionsApiV1CurationDecisionsBulkRejectPostResponse,
  AxiosError<BulkRejectDecisionsApiV1CurationDecisionsBulkRejectPostError>,
  Options<BulkRejectDecisionsApiV1CurationDecisionsBulkRejectPostData>
> => {
  const mutationOptions: UseMutationOptions<
    BulkRejectDecisionsApiV1CurationDecisionsBulkRejectPostResponse,
    AxiosError<BulkRejectDecisionsApiV1CurationDecisionsBulkRejectPostError>,
    Options<BulkRejectDecisionsApiV1CurationDecisionsBulkRejectPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } =
        await bulkRejectDecisionsApiV1CurationDecisionsBulkRejectPost({
          ...options,
          ...fnOptions,
          throwOnError: true
        })
      return data
    }
  }
  return mutationOptions
}

export const getStatisticsApiV1CurationStatsGetQueryKey = (
  options?: Options<GetStatisticsApiV1CurationStatsGetData>
) => createQueryKey('getStatisticsApiV1CurationStatsGet', options)

/**
 * Get Statistics
 *
 * Retrieve registry statistics and curation statistics with optional filtering.
 */
export const getStatisticsApiV1CurationStatsGetOptions = (
  options?: Options<GetStatisticsApiV1CurationStatsGetData>
) =>
  queryOptions<
    GetStatisticsApiV1CurationStatsGetResponse,
    AxiosError<GetStatisticsApiV1CurationStatsGetError>,
    GetStatisticsApiV1CurationStatsGetResponse,
    ReturnType<typeof getStatisticsApiV1CurationStatsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getStatisticsApiV1CurationStatsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: getStatisticsApiV1CurationStatsGetQueryKey(options)
  })

export const listUserActionsApiV1UserActionsGetQueryKey = (
  options?: Options<ListUserActionsApiV1UserActionsGetData>
) => createQueryKey('listUserActionsApiV1UserActionsGet', options)

/**
 * List User Actions
 *
 * List paginated user actions ordered by latest first (admin only).
 */
export const listUserActionsApiV1UserActionsGetOptions = (
  options?: Options<ListUserActionsApiV1UserActionsGetData>
) =>
  queryOptions<
    ListUserActionsApiV1UserActionsGetResponse,
    AxiosError<ListUserActionsApiV1UserActionsGetError>,
    ListUserActionsApiV1UserActionsGetResponse,
    ReturnType<typeof listUserActionsApiV1UserActionsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listUserActionsApiV1UserActionsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: listUserActionsApiV1UserActionsGetQueryKey(options)
  })

export const listUserActionsApiV1UserActionsGetInfiniteQueryKey = (
  options?: Options<ListUserActionsApiV1UserActionsGetData>
): QueryKey<Options<ListUserActionsApiV1UserActionsGetData>> =>
  createQueryKey('listUserActionsApiV1UserActionsGet', options, true)

/**
 * List User Actions
 *
 * List paginated user actions ordered by latest first (admin only).
 */
export const listUserActionsApiV1UserActionsGetInfiniteOptions = (
  options?: Options<ListUserActionsApiV1UserActionsGetData>
) =>
  infiniteQueryOptions<
    ListUserActionsApiV1UserActionsGetResponse,
    AxiosError<ListUserActionsApiV1UserActionsGetError>,
    InfiniteData<ListUserActionsApiV1UserActionsGetResponse>,
    QueryKey<Options<ListUserActionsApiV1UserActionsGetData>>,
    | number
    | Pick<
        QueryKey<Options<ListUserActionsApiV1UserActionsGetData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListUserActionsApiV1UserActionsGetData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam
                }
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await listUserActionsApiV1UserActionsGet({
          ...options,
          ...params,
          signal,
          throwOnError: true
        })
        return data
      },
      queryKey: listUserActionsApiV1UserActionsGetInfiniteQueryKey(options)
    }
  )

export const listUsersApiV1UsersGetQueryKey = (
  options?: Options<ListUsersApiV1UsersGetData>
) => createQueryKey('listUsersApiV1UsersGet', options)

/**
 * List Users
 *
 * List all users (admin only).
 */
export const listUsersApiV1UsersGetOptions = (
  options?: Options<ListUsersApiV1UsersGetData>
) =>
  queryOptions<
    ListUsersApiV1UsersGetResponse,
    AxiosError<ListUsersApiV1UsersGetError>,
    ListUsersApiV1UsersGetResponse,
    ReturnType<typeof listUsersApiV1UsersGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listUsersApiV1UsersGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: listUsersApiV1UsersGetQueryKey(options)
  })

export const listUsersApiV1UsersGetInfiniteQueryKey = (
  options?: Options<ListUsersApiV1UsersGetData>
): QueryKey<Options<ListUsersApiV1UsersGetData>> =>
  createQueryKey('listUsersApiV1UsersGet', options, true)

/**
 * List Users
 *
 * List all users (admin only).
 */
export const listUsersApiV1UsersGetInfiniteOptions = (
  options?: Options<ListUsersApiV1UsersGetData>
) =>
  infiniteQueryOptions<
    ListUsersApiV1UsersGetResponse,
    AxiosError<ListUsersApiV1UsersGetError>,
    InfiniteData<ListUsersApiV1UsersGetResponse>,
    QueryKey<Options<ListUsersApiV1UsersGetData>>,
    | number
    | Pick<
        QueryKey<Options<ListUsersApiV1UsersGetData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListUsersApiV1UsersGetData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam
                }
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await listUsersApiV1UsersGet({
          ...options,
          ...params,
          signal,
          throwOnError: true
        })
        return data
      },
      queryKey: listUsersApiV1UsersGetInfiniteQueryKey(options)
    }
  )

/**
 * Create User
 *
 * Create a new user (admin only).
 */
export const createUserApiV1UsersPostMutation = (
  options?: Partial<Options<CreateUserApiV1UsersPostData>>
): UseMutationOptions<
  CreateUserApiV1UsersPostResponse,
  AxiosError<CreateUserApiV1UsersPostError>,
  Options<CreateUserApiV1UsersPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateUserApiV1UsersPostResponse,
    AxiosError<CreateUserApiV1UsersPostError>,
    Options<CreateUserApiV1UsersPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createUserApiV1UsersPost({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

/**
 * Patch User
 *
 * Update user flags (admin only).
 */
export const patchUserApiV1UsersUserIdPatchMutation = (
  options?: Partial<Options<PatchUserApiV1UsersUserIdPatchData>>
): UseMutationOptions<
  PatchUserApiV1UsersUserIdPatchResponse,
  AxiosError<PatchUserApiV1UsersUserIdPatchError>,
  Options<PatchUserApiV1UsersUserIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    PatchUserApiV1UsersUserIdPatchResponse,
    AxiosError<PatchUserApiV1UsersUserIdPatchError>,
    Options<PatchUserApiV1UsersUserIdPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await patchUserApiV1UsersUserIdPatch({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

export const getCurrentUserApiV1UsersMeGetQueryKey = (
  options?: Options<GetCurrentUserApiV1UsersMeGetData>
) => createQueryKey('getCurrentUserApiV1UsersMeGet', options)

/**
 * Get Current User
 *
 * Get current authenticated user.
 */
export const getCurrentUserApiV1UsersMeGetOptions = (
  options?: Options<GetCurrentUserApiV1UsersMeGetData>
) =>
  queryOptions<
    GetCurrentUserApiV1UsersMeGetResponse,
    AxiosError<GetCurrentUserApiV1UsersMeGetError>,
    GetCurrentUserApiV1UsersMeGetResponse,
    ReturnType<typeof getCurrentUserApiV1UsersMeGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCurrentUserApiV1UsersMeGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: getCurrentUserApiV1UsersMeGetQueryKey(options)
  })
