// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions
} from '@tanstack/react-query'
import type { AxiosError } from 'axios'

import { client } from '../client.gen'
import {
  curationDecisionsAcceptCreate,
  curationDecisionsAlternativeCanonicalEntitiesRetrieve,
  curationDecisionsAssignCreate,
  curationDecisionsProposedCanonicalEntityRetrieve,
  curationDecisionsRejectCreate,
  curationDecisionsRetrieve,
  curationEntitiesRetrieve,
  curationStatsRetrieve,
  healthRetrieve,
  type Options
} from '../sdk.gen'
import type {
  CurationDecisionsAcceptCreateData,
  CurationDecisionsAcceptCreateError,
  CurationDecisionsAcceptCreateResponse,
  CurationDecisionsAlternativeCanonicalEntitiesRetrieveData,
  CurationDecisionsAlternativeCanonicalEntitiesRetrieveError,
  CurationDecisionsAlternativeCanonicalEntitiesRetrieveResponse,
  CurationDecisionsAssignCreateData,
  CurationDecisionsAssignCreateError,
  CurationDecisionsAssignCreateResponse,
  CurationDecisionsProposedCanonicalEntityRetrieveData,
  CurationDecisionsProposedCanonicalEntityRetrieveError,
  CurationDecisionsProposedCanonicalEntityRetrieveResponse,
  CurationDecisionsRejectCreateData,
  CurationDecisionsRejectCreateError,
  CurationDecisionsRejectCreateResponse,
  CurationDecisionsRetrieveData,
  CurationDecisionsRetrieveResponse,
  CurationEntitiesRetrieveData,
  CurationEntitiesRetrieveError,
  CurationEntitiesRetrieveResponse,
  CurationStatsRetrieveData,
  CurationStatsRetrieveResponse,
  HealthRetrieveData
} from '../types.gen'

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string
    _infinite?: boolean
    tags?: ReadonlyArray<string>
  }
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (tags) {
    params.tags = tags
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

export const curationDecisionsRetrieveQueryKey = (
  options?: Options<CurationDecisionsRetrieveData>
) => createQueryKey('curationDecisionsRetrieve', options)

/**
 * List decisions
 *
 * Retrieve paginated list of decisions with optional filtering. By default returns only PENDING_MANUAL_REVIEW decisions.
 */
export const curationDecisionsRetrieveOptions = (
  options?: Options<CurationDecisionsRetrieveData>
) =>
  queryOptions<
    CurationDecisionsRetrieveResponse,
    AxiosError<DefaultError>,
    CurationDecisionsRetrieveResponse,
    ReturnType<typeof curationDecisionsRetrieveQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await curationDecisionsRetrieve({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: curationDecisionsRetrieveQueryKey(options)
  })

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>
>(
  queryKey: QueryKey<Options>,
  page: K
) => {
  const params = { ...queryKey[0] }
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any)
    }
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers
    }
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any)
    }
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any)
    }
  }
  return params as unknown as typeof page
}

export const curationDecisionsRetrieveInfiniteQueryKey = (
  options?: Options<CurationDecisionsRetrieveData>
): QueryKey<Options<CurationDecisionsRetrieveData>> =>
  createQueryKey('curationDecisionsRetrieve', options, true)

/**
 * List decisions
 *
 * Retrieve paginated list of decisions with optional filtering. By default returns only PENDING_MANUAL_REVIEW decisions.
 */
export const curationDecisionsRetrieveInfiniteOptions = (
  options?: Options<CurationDecisionsRetrieveData>
) =>
  infiniteQueryOptions<
    CurationDecisionsRetrieveResponse,
    AxiosError<DefaultError>,
    InfiniteData<CurationDecisionsRetrieveResponse>,
    QueryKey<Options<CurationDecisionsRetrieveData>>,
    | number
    | Pick<
        QueryKey<Options<CurationDecisionsRetrieveData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<CurationDecisionsRetrieveData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam
                }
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await curationDecisionsRetrieve({
          ...options,
          ...params,
          signal,
          throwOnError: true
        })
        return data
      },
      queryKey: curationDecisionsRetrieveInfiniteQueryKey(options)
    }
  )

/**
 * Accept proposed match
 *
 * Accept the proposed canonical entity match. Sets alignment confidence to 1.
 */
export const curationDecisionsAcceptCreateMutation = (
  options?: Partial<Options<CurationDecisionsAcceptCreateData>>
): UseMutationOptions<
  CurationDecisionsAcceptCreateResponse,
  AxiosError<CurationDecisionsAcceptCreateError>,
  Options<CurationDecisionsAcceptCreateData>
> => {
  const mutationOptions: UseMutationOptions<
    CurationDecisionsAcceptCreateResponse,
    AxiosError<CurationDecisionsAcceptCreateError>,
    Options<CurationDecisionsAcceptCreateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await curationDecisionsAcceptCreate({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

export const curationDecisionsAlternativeCanonicalEntitiesRetrieveQueryKey = (
  options: Options<CurationDecisionsAlternativeCanonicalEntitiesRetrieveData>
) =>
  createQueryKey(
    'curationDecisionsAlternativeCanonicalEntitiesRetrieve',
    options
  )

/**
 * Get alternative matches
 *
 * Retrieve alternative match clusters for a decision (paginated). Returns all canonical entity clusters except the proposed match, with top 5 alignment links including full entity mention data.
 */
export const curationDecisionsAlternativeCanonicalEntitiesRetrieveOptions = (
  options: Options<CurationDecisionsAlternativeCanonicalEntitiesRetrieveData>
) =>
  queryOptions<
    CurationDecisionsAlternativeCanonicalEntitiesRetrieveResponse,
    AxiosError<CurationDecisionsAlternativeCanonicalEntitiesRetrieveError>,
    CurationDecisionsAlternativeCanonicalEntitiesRetrieveResponse,
    ReturnType<
      typeof curationDecisionsAlternativeCanonicalEntitiesRetrieveQueryKey
    >
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } =
        await curationDecisionsAlternativeCanonicalEntitiesRetrieve({
          ...options,
          ...queryKey[0],
          signal,
          throwOnError: true
        })
      return data
    },
    queryKey:
      curationDecisionsAlternativeCanonicalEntitiesRetrieveQueryKey(options)
  })

export const curationDecisionsAlternativeCanonicalEntitiesRetrieveInfiniteQueryKey =
  (
    options: Options<CurationDecisionsAlternativeCanonicalEntitiesRetrieveData>
  ): QueryKey<
    Options<CurationDecisionsAlternativeCanonicalEntitiesRetrieveData>
  > =>
    createQueryKey(
      'curationDecisionsAlternativeCanonicalEntitiesRetrieve',
      options,
      true
    )

/**
 * Get alternative matches
 *
 * Retrieve alternative match clusters for a decision (paginated). Returns all canonical entity clusters except the proposed match, with top 5 alignment links including full entity mention data.
 */
export const curationDecisionsAlternativeCanonicalEntitiesRetrieveInfiniteOptions =
  (
    options: Options<CurationDecisionsAlternativeCanonicalEntitiesRetrieveData>
  ) =>
    infiniteQueryOptions<
      CurationDecisionsAlternativeCanonicalEntitiesRetrieveResponse,
      AxiosError<CurationDecisionsAlternativeCanonicalEntitiesRetrieveError>,
      InfiniteData<CurationDecisionsAlternativeCanonicalEntitiesRetrieveResponse>,
      QueryKey<
        Options<CurationDecisionsAlternativeCanonicalEntitiesRetrieveData>
      >,
      | number
      | Pick<
          QueryKey<
            Options<CurationDecisionsAlternativeCanonicalEntitiesRetrieveData>
          >[0],
          'body' | 'headers' | 'path' | 'query'
        >
    >(
      // @ts-ignore
      {
        queryFn: async ({ pageParam, queryKey, signal }) => {
          // @ts-ignore
          const page: Pick<
            QueryKey<
              Options<CurationDecisionsAlternativeCanonicalEntitiesRetrieveData>
            >[0],
            'body' | 'headers' | 'path' | 'query'
          > =
            typeof pageParam === 'object'
              ? pageParam
              : {
                  query: {
                    page: pageParam
                  }
                }
          const params = createInfiniteParams(queryKey, page)
          const { data } =
            await curationDecisionsAlternativeCanonicalEntitiesRetrieve({
              ...options,
              ...params,
              signal,
              throwOnError: true
            })
          return data
        },
        queryKey:
          curationDecisionsAlternativeCanonicalEntitiesRetrieveInfiniteQueryKey(
            options
          )
      }
    )

/**
 * Assign to alternative canonical entity
 *
 * Assign the entity mention to a different canonical entity. Creates new alignment link with confidence 1. Existing alignment link receives confidence -1.
 */
export const curationDecisionsAssignCreateMutation = (
  options?: Partial<Options<CurationDecisionsAssignCreateData>>
): UseMutationOptions<
  CurationDecisionsAssignCreateResponse,
  AxiosError<CurationDecisionsAssignCreateError>,
  Options<CurationDecisionsAssignCreateData>
> => {
  const mutationOptions: UseMutationOptions<
    CurationDecisionsAssignCreateResponse,
    AxiosError<CurationDecisionsAssignCreateError>,
    Options<CurationDecisionsAssignCreateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await curationDecisionsAssignCreate({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

export const curationDecisionsProposedCanonicalEntityRetrieveQueryKey = (
  options: Options<CurationDecisionsProposedCanonicalEntityRetrieveData>
) => createQueryKey('curationDecisionsProposedCanonicalEntityRetrieve', options)

/**
 * Get proposed match
 *
 * Retrieve the proposed match cluster for a decision. Returns the highest confidence canonical entity with top 5 alignment links including full entity mention data.
 */
export const curationDecisionsProposedCanonicalEntityRetrieveOptions = (
  options: Options<CurationDecisionsProposedCanonicalEntityRetrieveData>
) =>
  queryOptions<
    CurationDecisionsProposedCanonicalEntityRetrieveResponse,
    AxiosError<CurationDecisionsProposedCanonicalEntityRetrieveError>,
    CurationDecisionsProposedCanonicalEntityRetrieveResponse,
    ReturnType<typeof curationDecisionsProposedCanonicalEntityRetrieveQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await curationDecisionsProposedCanonicalEntityRetrieve({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: curationDecisionsProposedCanonicalEntityRetrieveQueryKey(options)
  })

/**
 * Reject proposed match
 *
 * Reject the proposed match. Sets alignment confidence to -1.
 */
export const curationDecisionsRejectCreateMutation = (
  options?: Partial<Options<CurationDecisionsRejectCreateData>>
): UseMutationOptions<
  CurationDecisionsRejectCreateResponse,
  AxiosError<CurationDecisionsRejectCreateError>,
  Options<CurationDecisionsRejectCreateData>
> => {
  const mutationOptions: UseMutationOptions<
    CurationDecisionsRejectCreateResponse,
    AxiosError<CurationDecisionsRejectCreateError>,
    Options<CurationDecisionsRejectCreateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await curationDecisionsRejectCreate({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

export const curationEntitiesRetrieveQueryKey = (
  options: Options<CurationEntitiesRetrieveData>
) => createQueryKey('curationEntitiesRetrieve', options)

/**
 * Get entity mention
 *
 * Retrieve entity mention by identifier with parsed data for UI display (excludes raw payload)
 */
export const curationEntitiesRetrieveOptions = (
  options: Options<CurationEntitiesRetrieveData>
) =>
  queryOptions<
    CurationEntitiesRetrieveResponse,
    AxiosError<CurationEntitiesRetrieveError>,
    CurationEntitiesRetrieveResponse,
    ReturnType<typeof curationEntitiesRetrieveQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await curationEntitiesRetrieve({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: curationEntitiesRetrieveQueryKey(options)
  })

export const curationStatsRetrieveQueryKey = (
  options?: Options<CurationStatsRetrieveData>
) => createQueryKey('curationStatsRetrieve', options)

/**
 * Get statistics
 *
 * Retrieve curation and registry statistics with optional timeframe filtering
 */
export const curationStatsRetrieveOptions = (
  options?: Options<CurationStatsRetrieveData>
) =>
  queryOptions<
    CurationStatsRetrieveResponse,
    AxiosError<DefaultError>,
    CurationStatsRetrieveResponse,
    ReturnType<typeof curationStatsRetrieveQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await curationStatsRetrieve({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: curationStatsRetrieveQueryKey(options)
  })

export const healthRetrieveQueryKey = (options?: Options<HealthRetrieveData>) =>
  createQueryKey('healthRetrieve', options)

export const healthRetrieveOptions = (options?: Options<HealthRetrieveData>) =>
  queryOptions<
    unknown,
    AxiosError<DefaultError>,
    unknown,
    ReturnType<typeof healthRetrieveQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await healthRetrieve({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: healthRetrieveQueryKey(options)
  })
