---
apiVersion: v2
type: application
name: app
version: 0.1.0
description: 'Main Helm chart for the app'

dependencies:
  - alias: app
    repository: https://gitlab.devebs.net/api/v4/projects/1210/packages/helm/stable/
    name: common
    version: '>= 0.1.0, < 1.0.0'
