// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client'
import { client } from './client.gen'
import type {
  CurationDecisionsAcceptCreateData,
  CurationDecisionsAcceptCreateErrors,
  CurationDecisionsAcceptCreateResponses,
  CurationDecisionsAlternativeCanonicalEntitiesRetrieveData,
  CurationDecisionsAlternativeCanonicalEntitiesRetrieveErrors,
  CurationDecisionsAlternativeCanonicalEntitiesRetrieveResponses,
  CurationDecisionsAssignCreateData,
  CurationDecisionsAssignCreateErrors,
  CurationDecisionsAssignCreateResponses,
  CurationDecisionsProposedCanonicalEntityRetrieveData,
  CurationDecisionsProposedCanonicalEntityRetrieveErrors,
  CurationDecisionsProposedCanonicalEntityRetrieveResponses,
  CurationDecisionsRejectCreateData,
  CurationDecisionsRejectCreateErrors,
  CurationDecisionsRejectCreateResponses,
  CurationDecisionsRetrieveData,
  CurationDecisionsRetrieveResponses,
  CurationEntitiesRetrieveData,
  CurationEntitiesRetrieveErrors,
  CurationEntitiesRetrieveResponses,
  CurationStatsRetrieveData,
  CurationStatsRetrieveResponses,
  HealthRetrieveData,
  HealthRetrieveResponses
} from './types.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

/**
 * List decisions
 *
 * Retrieve paginated list of decisions with optional filtering. By default returns only PENDING_MANUAL_REVIEW decisions.
 */
export const curationDecisionsRetrieve = <ThrowOnError extends boolean = false>(
  options?: Options<CurationDecisionsRetrieveData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    CurationDecisionsRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        in: 'cookie',
        name: 'sessionid',
        type: 'apiKey'
      },
      { scheme: 'basic', type: 'http' }
    ],
    url: '/api/v1/curation/decisions',
    ...options
  })

/**
 * Accept proposed match
 *
 * Accept the proposed canonical entity match. Sets alignment confidence to 1.
 */
export const curationDecisionsAcceptCreate = <
  ThrowOnError extends boolean = false
>(
  options: Options<CurationDecisionsAcceptCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CurationDecisionsAcceptCreateResponses,
    CurationDecisionsAcceptCreateErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        in: 'cookie',
        name: 'sessionid',
        type: 'apiKey'
      },
      { scheme: 'basic', type: 'http' }
    ],
    url: '/api/v1/curation/decisions/{id}/accept',
    ...options
  })

/**
 * Get alternative matches
 *
 * Retrieve alternative match clusters for a decision (paginated). Returns all canonical entity clusters except the proposed match, with top 5 alignment links including full entity mention data.
 */
export const curationDecisionsAlternativeCanonicalEntitiesRetrieve = <
  ThrowOnError extends boolean = false
>(
  options: Options<
    CurationDecisionsAlternativeCanonicalEntitiesRetrieveData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    CurationDecisionsAlternativeCanonicalEntitiesRetrieveResponses,
    CurationDecisionsAlternativeCanonicalEntitiesRetrieveErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        in: 'cookie',
        name: 'sessionid',
        type: 'apiKey'
      },
      { scheme: 'basic', type: 'http' }
    ],
    url: '/api/v1/curation/decisions/{id}/alternative-canonical-entities',
    ...options
  })

/**
 * Assign to alternative canonical entity
 *
 * Assign the entity mention to a different canonical entity. Creates new alignment link with confidence 1. Existing alignment link receives confidence -1.
 */
export const curationDecisionsAssignCreate = <
  ThrowOnError extends boolean = false
>(
  options: Options<CurationDecisionsAssignCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CurationDecisionsAssignCreateResponses,
    CurationDecisionsAssignCreateErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        in: 'cookie',
        name: 'sessionid',
        type: 'apiKey'
      },
      { scheme: 'basic', type: 'http' }
    ],
    url: '/api/v1/curation/decisions/{id}/assign',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })

/**
 * Get proposed match
 *
 * Retrieve the proposed match cluster for a decision. Returns the highest confidence canonical entity with top 5 alignment links including full entity mention data.
 */
export const curationDecisionsProposedCanonicalEntityRetrieve = <
  ThrowOnError extends boolean = false
>(
  options: Options<
    CurationDecisionsProposedCanonicalEntityRetrieveData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    CurationDecisionsProposedCanonicalEntityRetrieveResponses,
    CurationDecisionsProposedCanonicalEntityRetrieveErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        in: 'cookie',
        name: 'sessionid',
        type: 'apiKey'
      },
      { scheme: 'basic', type: 'http' }
    ],
    url: '/api/v1/curation/decisions/{id}/proposed-canonical-entity',
    ...options
  })

/**
 * Reject proposed match
 *
 * Reject the proposed match. Sets alignment confidence to -1.
 */
export const curationDecisionsRejectCreate = <
  ThrowOnError extends boolean = false
>(
  options: Options<CurationDecisionsRejectCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CurationDecisionsRejectCreateResponses,
    CurationDecisionsRejectCreateErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        in: 'cookie',
        name: 'sessionid',
        type: 'apiKey'
      },
      { scheme: 'basic', type: 'http' }
    ],
    url: '/api/v1/curation/decisions/{id}/reject',
    ...options
  })

/**
 * Get entity mention
 *
 * Retrieve entity mention by identifier with parsed data for UI display (excludes raw payload)
 */
export const curationEntitiesRetrieve = <ThrowOnError extends boolean = false>(
  options: Options<CurationEntitiesRetrieveData, ThrowOnError>
) =>
  (options.client ?? client).get<
    CurationEntitiesRetrieveResponses,
    CurationEntitiesRetrieveErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        in: 'cookie',
        name: 'sessionid',
        type: 'apiKey'
      },
      { scheme: 'basic', type: 'http' }
    ],
    url: '/api/v1/curation/entities/{id}',
    ...options
  })

/**
 * Get statistics
 *
 * Retrieve curation and registry statistics with optional timeframe filtering
 */
export const curationStatsRetrieve = <ThrowOnError extends boolean = false>(
  options?: Options<CurationStatsRetrieveData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    CurationStatsRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        in: 'cookie',
        name: 'sessionid',
        type: 'apiKey'
      },
      { scheme: 'basic', type: 'http' }
    ],
    url: '/api/v1/curation/stats',
    ...options
  })

export const healthRetrieve = <ThrowOnError extends boolean = false>(
  options?: Options<HealthRetrieveData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    HealthRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: 'cookie',
        name: 'sessionid',
        type: 'apiKey'
      },
      { scheme: 'basic', type: 'http' }
    ],
    url: '/health',
    ...options
  })
