// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: 'https://api.ers.meaningfy.dev.devebs.net' | (string & {})
}

/**
 * An asserted correspondence between an entity mention and a canonical entity.
 */
export type AlignmentLink = {
  /**
   * URI of the entity mention
   */
  mention_identifier: string
  /**
   * URI of the canonical entity
   */
  canonical_identifier: string
  /**
   * Confidence score ranging from -1 (rejected) to 1 (confirmed)
   */
  confidence_score: number
}

/**
 * Alignment link with embedded entity mention data.
 */
export type AlignmentLinkDetail = {
  /**
   * Full entity mention data
   */
  entity_mention: EntityMentionResponse
  /**
   * URI of the canonical entity
   */
  canonical_identifier: string
  /**
   * Confidence score ranging from -1 (rejected) to 1 (confirmed)
   */
  confidence_score: number
}

/**
 * Context for a curation decision including alignment options.
 */
export type AlignmentOptionSet = {
  /**
   * URI of the entity mention being resolved
   */
  subject_entity_mention_identifier: string
  /**
   * Human-readable name extracted from the entity for UI display
   */
  subject_entity_display_name?: string
  /**
   * Candidate alignment links with confidence scores
   */
  alignment_options: Array<AlignmentLink>
}

/**
 * Request body for assigning entity to alternative canonical entity.
 */
export type AssignDecisionRequest = {
  /**
   * Target canonical entity to assign the entity mention to
   */
  canonical_entity_id: string
}

/**
 * Preview of a canonical entity with detailed alignment links.
 */
export type CanonicalEntityPreview = {
  /**
   * Canonical entity URI identifier
   */
  identifier: string
  created_at: string
  /**
   * Confidence score that the subject entity belongs to this canonical entity (from alignment options)
   */
  confidence_score: number
  /**
   * Top 5 alignment links with full entity mention data
   */
  top_alignment_links: Array<AlignmentLinkDetail>
}

/**
 * Curation statistics.
 */
export type CurationStatistics = {
  pending_decisions: number
  reviewed_decisions: number
  automatic_decisions: number
}

/**
 * A resolution decision containing alignment options for curation.
 */
export type Decision = {
  /**
   * Unique identifier for the decision
   */
  id: string
  created_at: string
  updated_at: string
  decision_context: AlignmentOptionSet
  decision_status: DecisionStatusEnum
  decision_action: DecisionActionEnum
}

/**
 * * `ACCEPT_TOP` - ACCEPT_TOP
 * * `ACCEPT_ALTERNATIVE` - ACCEPT_ALTERNATIVE
 * * `REJECT_ALL` - REJECT_ALL
 */
export const DecisionActionEnum = {
  ACCEPT_TOP: 'ACCEPT_TOP',
  ACCEPT_ALTERNATIVE: 'ACCEPT_ALTERNATIVE',
  REJECT_ALL: 'REJECT_ALL'
} as const

/**
 * * `ACCEPT_TOP` - ACCEPT_TOP
 * * `ACCEPT_ALTERNATIVE` - ACCEPT_ALTERNATIVE
 * * `REJECT_ALL` - REJECT_ALL
 */
export type DecisionActionEnum =
  (typeof DecisionActionEnum)[keyof typeof DecisionActionEnum]

/**
 * * `AUTOMATIC_CONFIDENT` - AUTOMATIC_CONFIDENT
 * * `PENDING_MANUAL_REVIEW` - PENDING_MANUAL_REVIEW
 * * `MANUALLY_REVIEWED` - MANUALLY_REVIEWED
 */
export const DecisionStatusEnum = {
  AUTOMATIC_CONFIDENT: 'AUTOMATIC_CONFIDENT',
  PENDING_MANUAL_REVIEW: 'PENDING_MANUAL_REVIEW',
  MANUALLY_REVIEWED: 'MANUALLY_REVIEWED'
} as const

/**
 * * `AUTOMATIC_CONFIDENT` - AUTOMATIC_CONFIDENT
 * * `PENDING_MANUAL_REVIEW` - PENDING_MANUAL_REVIEW
 * * `MANUALLY_REVIEWED` - MANUALLY_REVIEWED
 */
export type DecisionStatusEnum =
  (typeof DecisionStatusEnum)[keyof typeof DecisionStatusEnum]

/**
 * Entity mention data for API responses (excludes raw payload).
 */
export type EntityMentionResponse = {
  /**
   * URI identifier
   */
  identifier: string
  type: TypeEnum
  /**
   * Parsed JSON representation for UI display
   */
  parsed_data: unknown
}

/**
 * Response confirming successful action execution.
 */
export type ExecutionAcknowledgement = {
  /**
   * UUID of the decision
   */
  decision_id: string
  decision_action: DecisionActionEnum
  executed_at: string
}

/**
 * Standard HTTP error response.
 */
export type HttpError = {
  /**
   * Error message
   */
  detail: string
}

/**
 * Paginated list of canonical entity previews.
 */
export type PaginatedCanonicalEntityPreview = {
  /**
   * Total number of items
   */
  count: number
  /**
   * Previous page number, null if on first page
   */
  previous: number | null
  /**
   * Next page number, null if on last page
   */
  next: number | null
  /**
   * Array of canonical entity previews for current page
   */
  results: Array<CanonicalEntityPreview>
}

/**
 * Paginated list of decisions response.
 */
export type PaginatedDecisionList = {
  /**
   * Total number of items
   */
  count: number
  /**
   * Previous page number, null if on first page
   */
  previous: number | null
  /**
   * Next page number, null if on last page
   */
  next: number | null
  /**
   * Array of decisions for current page
   */
  results: Array<Decision>
}

/**
 * Registry statistics.
 */
export type RegistryStatistics = {
  canonical_entities: number
  average_mentions_per_entity: number
  entity_mentions: number
  resolution_requests: number
}

/**
 * Statistics response containing registry and curation statistics.
 */
export type StatisticsResponse = {
  registry_statistics: RegistryStatistics
  curation_statistics: CurationStatistics
}

/**
 * * `ORGANISATION` - ORGANISATION
 * * `PROCEDURE` - PROCEDURE
 */
export const TypeEnum = {
  ORGANISATION: 'ORGANISATION',
  PROCEDURE: 'PROCEDURE'
} as const

/**
 * * `ORGANISATION` - ORGANISATION
 * * `PROCEDURE` - PROCEDURE
 */
export type TypeEnum = (typeof TypeEnum)[keyof typeof TypeEnum]

export type CurationDecisionsRetrieveData = {
  body?: never
  path?: never
  query?: {
    /**
     * Maximum confidence score
     */
    confidence_max?: number
    /**
     * Minimum confidence score
     */
    confidence_min?: number
    /**
     * Filter by entity type
     */
    entity_type?: 'ORGANISATION' | 'PROCEDURE'
    /**
     * Sort field with direction prefix
     */
    ordering?:
      | '+confidence_score'
      | '+created_at'
      | '+updated_at'
      | '-confidence_score'
      | '-created_at'
      | '-updated_at'
    /**
     * Page number (1-indexed)
     */
    page?: number
    /**
     * Items per page (max 100)
     */
    per_page?: number
    /**
     * Text search in entity representation
     */
    search?: string
    /**
     * Filter by decision status
     */
    status?:
      | 'AUTOMATIC_CONFIDENT'
      | 'MANUALLY_REVIEWED'
      | 'PENDING_MANUAL_REVIEW'
  }
  url: '/api/v1/curation/decisions'
}

export type CurationDecisionsRetrieveResponses = {
  200: PaginatedDecisionList
}

export type CurationDecisionsRetrieveResponse =
  CurationDecisionsRetrieveResponses[keyof CurationDecisionsRetrieveResponses]

export type CurationDecisionsAcceptCreateData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/curation/decisions/{id}/accept'
}

export type CurationDecisionsAcceptCreateErrors = {
  404: HttpError
  409: HttpError
}

export type CurationDecisionsAcceptCreateError =
  CurationDecisionsAcceptCreateErrors[keyof CurationDecisionsAcceptCreateErrors]

export type CurationDecisionsAcceptCreateResponses = {
  200: ExecutionAcknowledgement
}

export type CurationDecisionsAcceptCreateResponse =
  CurationDecisionsAcceptCreateResponses[keyof CurationDecisionsAcceptCreateResponses]

export type CurationDecisionsAlternativeCanonicalEntitiesRetrieveData = {
  body?: never
  path: {
    id: string
  }
  query?: {
    /**
     * Page number (1-indexed)
     */
    page?: number
    /**
     * Items per page (max 100)
     */
    per_page?: number
  }
  url: '/api/v1/curation/decisions/{id}/alternative-canonical-entities'
}

export type CurationDecisionsAlternativeCanonicalEntitiesRetrieveErrors = {
  404: HttpError
}

export type CurationDecisionsAlternativeCanonicalEntitiesRetrieveError =
  CurationDecisionsAlternativeCanonicalEntitiesRetrieveErrors[keyof CurationDecisionsAlternativeCanonicalEntitiesRetrieveErrors]

export type CurationDecisionsAlternativeCanonicalEntitiesRetrieveResponses = {
  200: PaginatedCanonicalEntityPreview
}

export type CurationDecisionsAlternativeCanonicalEntitiesRetrieveResponse =
  CurationDecisionsAlternativeCanonicalEntitiesRetrieveResponses[keyof CurationDecisionsAlternativeCanonicalEntitiesRetrieveResponses]

export type CurationDecisionsAssignCreateData = {
  body: AssignDecisionRequest
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/curation/decisions/{id}/assign'
}

export type CurationDecisionsAssignCreateErrors = {
  404: HttpError
  409: HttpError
}

export type CurationDecisionsAssignCreateError =
  CurationDecisionsAssignCreateErrors[keyof CurationDecisionsAssignCreateErrors]

export type CurationDecisionsAssignCreateResponses = {
  200: ExecutionAcknowledgement
}

export type CurationDecisionsAssignCreateResponse =
  CurationDecisionsAssignCreateResponses[keyof CurationDecisionsAssignCreateResponses]

export type CurationDecisionsProposedCanonicalEntityRetrieveData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/curation/decisions/{id}/proposed-canonical-entity'
}

export type CurationDecisionsProposedCanonicalEntityRetrieveErrors = {
  404: HttpError
}

export type CurationDecisionsProposedCanonicalEntityRetrieveError =
  CurationDecisionsProposedCanonicalEntityRetrieveErrors[keyof CurationDecisionsProposedCanonicalEntityRetrieveErrors]

export type CurationDecisionsProposedCanonicalEntityRetrieveResponses = {
  200: CanonicalEntityPreview
}

export type CurationDecisionsProposedCanonicalEntityRetrieveResponse =
  CurationDecisionsProposedCanonicalEntityRetrieveResponses[keyof CurationDecisionsProposedCanonicalEntityRetrieveResponses]

export type CurationDecisionsRejectCreateData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/curation/decisions/{id}/reject'
}

export type CurationDecisionsRejectCreateErrors = {
  404: HttpError
  409: HttpError
}

export type CurationDecisionsRejectCreateError =
  CurationDecisionsRejectCreateErrors[keyof CurationDecisionsRejectCreateErrors]

export type CurationDecisionsRejectCreateResponses = {
  200: ExecutionAcknowledgement
}

export type CurationDecisionsRejectCreateResponse =
  CurationDecisionsRejectCreateResponses[keyof CurationDecisionsRejectCreateResponses]

export type CurationEntitiesRetrieveData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/curation/entities/{id}'
}

export type CurationEntitiesRetrieveErrors = {
  404: HttpError
}

export type CurationEntitiesRetrieveError =
  CurationEntitiesRetrieveErrors[keyof CurationEntitiesRetrieveErrors]

export type CurationEntitiesRetrieveResponses = {
  200: EntityMentionResponse
}

export type CurationEntitiesRetrieveResponse =
  CurationEntitiesRetrieveResponses[keyof CurationEntitiesRetrieveResponses]

export type CurationStatsRetrieveData = {
  body?: never
  path?: never
  query?: {
    /**
     * Filter by entity type
     */
    entity_type?: 'ORGANISATION' | 'PROCEDURE'
    /**
     * End of the timeframe (ISO 8601 date-time)
     */
    timeframe_end?: string
    /**
     * Start of the timeframe (ISO 8601 date-time)
     */
    timeframe_start?: string
  }
  url: '/api/v1/curation/stats'
}

export type CurationStatsRetrieveResponses = {
  200: StatisticsResponse
}

export type CurationStatsRetrieveResponse =
  CurationStatsRetrieveResponses[keyof CurationStatsRetrieveResponses]

export type HealthRetrieveData = {
  body?: never
  path?: never
  query?: never
  url: '/health'
}

export type HealthRetrieveResponses = {
  /**
   * No response body
   */
  200: unknown
}
