// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: 'http://localhost:8000' | (string & {})
}

/**
 * AssignRequest
 *
 * Request body for assigning an entity to an alternative cluster.
 */
export type AssignRequest = {
  /**
   * Cluster Id
   */
  cluster_id: string
}

/**
 * BulkActionRequest
 *
 * Request body for bulk accept/reject operations.
 */
export type BulkActionRequest = {
  /**
   * Decision Ids
   */
  decision_ids: Array<string>
}

/**
 * BulkActionResponse
 *
 * Response body for bulk accept/reject operations.
 */
export type BulkActionResponse = {
  /**
   * Results
   */
  results: Array<BulkItemResult>
}

/**
 * BulkItemResult
 *
 * Result of a single decision within a bulk action.
 */
export type BulkItemResult = {
  /**
   * Decision Id
   */
  decision_id: string
  status: BulkItemStatus
  /**
   * Detail
   */
  detail?: string | null
}

/**
 * BulkItemStatus
 *
 * Outcome of an individual bulk action item.
 */
export const BulkItemStatus = {
  SUCCESS: 'success',
  NOT_FOUND: 'not_found',
  ALREADY_CURATED: 'already_curated',
  ERROR: 'error'
} as const

/**
 * BulkItemStatus
 *
 * Outcome of an individual bulk action item.
 */
export type BulkItemStatus =
  (typeof BulkItemStatus)[keyof typeof BulkItemStatus]

/**
 * CanonicalEntityPreview
 *
 * Cluster preview with top entity mentions for display.
 */
export type CanonicalEntityPreview = {
  /**
   * Cluster Id
   */
  cluster_id: string
  /**
   * Confidence Score
   */
  confidence_score: number
  /**
   * Similarity Score
   */
  similarity_score: number
  /**
   * Top Entities
   */
  top_entities: Array<EntityMentionPreview>
}

/**
 * ClusterReference
 *
 * A reference to a cluster to which an entity is deemed to belong, with an associated confidence and similarity scores.
 *
 * A cluster is a set of entity mentions that have been determined to refer to the same real-world entity.
 * Each cluster has a unique clusterId.
 *
 * A cluster reference is used to report the association between an entity mention and a cluster
 * of equivalence.
 */
export type ClusterReference = {
  /**
   * Cluster Id
   *
   * The identifier of the cluster/canonical entity that is considered equivalent to the
   * subject entity mention that an `EntityMentionResolutionResponse` refers to.
   *
   */
  cluster_id: string
  /**
   * Confidence Score
   *
   * A 0-1 value of how confident the ERE is about the equivalence between the subject entity mention
   * and the target canonical entity.
   *
   */
  confidence_score: number
  /**
   * Similarity Score
   *
   * A 0-1 score representing the pairwise comparison between a mention and a cluster (likely
   * based on a representative representation).
   *
   */
  similarity_score: number
}

/**
 * CreateUserRequest
 *
 * Admin request to create a user.
 */
export type CreateUserRequest = {
  /**
   * Email
   */
  email: string
  /**
   * Password
   */
  password: string
  /**
   * Is Active
   */
  is_active?: boolean
  /**
   * Is Superuser
   */
  is_superuser?: boolean
  /**
   * Is Verified
   */
  is_verified?: boolean
}

/**
 * CurationStatistics
 *
 * Statistics about the curation process based on UserAction counts.
 */
export type CurationStatistics = {
  /**
   * Total Decisions
   */
  total_decisions: number
  /**
   * Selected Top
   */
  selected_top: number
  /**
   * Selected Alternative
   */
  selected_alternative: number
  /**
   * Rejected All
   */
  rejected_all: number
}

/**
 * CursorPage[DecisionSummary]
 */
export type CursorPageDecisionSummary = {
  /**
   * Results
   */
  results: Array<DecisionSummary>
  /**
   * Next Cursor
   */
  next_cursor?: string | null
}

/**
 * DecisionOrdering
 *
 * Allowed ordering options for decision listing.
 */
export const DecisionOrdering = {
  CONFIDENCE_SCORE: 'confidence_score',
  '-CONFIDENCE_SCORE': '-confidence_score',
  CREATED_AT: 'created_at',
  '-CREATED_AT': '-created_at',
  UPDATED_AT: 'updated_at',
  '-UPDATED_AT': '-updated_at'
} as const

/**
 * DecisionOrdering
 *
 * Allowed ordering options for decision listing.
 */
export type DecisionOrdering =
  (typeof DecisionOrdering)[keyof typeof DecisionOrdering]

/**
 * DecisionSummary
 *
 * Decision summary for list display.
 */
export type DecisionSummary = {
  /**
   * Id
   */
  id: string
  about_entity_mention: EntityMentionPreview
  current_placement: ClusterReference
  /**
   * Created At
   */
  created_at: string
  /**
   * Updated At
   */
  updated_at?: string | null
}

/**
 * EntityMentionIdentifier
 *
 * A container that groups the attributes needed to identify an entity mention in a resolution request
 * or response.
 *
 * As per ERS architectural decision, in the whole ERS and ERE systems, there is always a deterministic
 * method to build a canonical identifier from the combination of `sourceId`, `requestId` and `entityType`
 * (eg, string concatenation plus some prefix). Similarly, a cluster ID (mentioned in various places in
 * in this hereby ERE service schema) can be built from an entity that is initially the only cluster member.
 */
export type EntityMentionIdentifier = {
  /**
   * Source Id
   *
   * The ID or URI of the ERS client that originated the request. This identifies an application or a
   * person accessing the ERS system.
   *
   */
  source_id: string
  /**
   * Request Id
   *
   * A string representing the unique ID of the request made to the ERS system. In general, this is unique
   * only within the scope of the source and the entity type, ie, within `sourceId` and `entityType`.
   *
   * Moreover, this is **not** the same as `ereRequestId`, which instead, is internal to the ERE and is
   * used to match responses to requests.
   *
   */
  request_id: string
  /**
   * Entity Type
   *
   * A string representing the entity type (based on CET). This is typically a URI.
   *
   * Note that this is at this level, and not at `EntityMention`, since, as said above,
   * it's needed to identify the entity, even when its content is not present. For the same
   * reason, it's used both for `EREResolutionRequest` and `EREResolutionResponse` messages.,
   *
   */
  entity_type: string
}

/**
 * EntityMentionPreview
 *
 * Lightweight entity mention projection for display.
 */
export type EntityMentionPreview = {
  identified_by: EntityMentionIdentifier
  /**
   * Parsed Representation
   */
  parsed_representation?: {
    [key: string]: unknown
  } | null
}

/**
 * ErrorResponse
 *
 * Standard error response body for OpenAPI documentation.
 */
export type ErrorResponse = {
  /**
   * Detail
   */
  detail: string
}

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>
}

/**
 * LoginRequest
 *
 * Request body for user login.
 */
export type LoginRequest = {
  /**
   * Email
   */
  email: string
  /**
   * Password
   */
  password: string
}

/**
 * PaginatedResult[CanonicalEntityPreview]
 */
export type PaginatedResultCanonicalEntityPreview = {
  /**
   * Count
   */
  count: number
  /**
   * Previous
   */
  previous?: number | null
  /**
   * Next
   */
  next?: number | null
  /**
   * Results
   */
  results: Array<CanonicalEntityPreview>
}

/**
 * PaginatedResult[UserActionSummary]
 */
export type PaginatedResultUserActionSummary = {
  /**
   * Count
   */
  count: number
  /**
   * Previous
   */
  previous?: number | null
  /**
   * Next
   */
  next?: number | null
  /**
   * Results
   */
  results: Array<UserActionSummary>
}

/**
 * PaginatedResult[UserResponse]
 */
export type PaginatedResultUserResponse = {
  /**
   * Count
   */
  count: number
  /**
   * Previous
   */
  previous?: number | null
  /**
   * Next
   */
  next?: number | null
  /**
   * Results
   */
  results: Array<UserResponse>
}

/**
 * RefreshRequest
 *
 * Request body for token refresh.
 */
export type RefreshRequest = {
  /**
   * Refresh Token
   */
  refresh_token: string
}

/**
 * RegisterRequest
 *
 * Request body for user registration.
 */
export type RegisterRequest = {
  /**
   * Email
   */
  email: string
  /**
   * Password
   */
  password: string
}

/**
 * RegistryStatistics
 *
 * Statistics about the entity registry.
 */
export type RegistryStatistics = {
  /**
   * Total Entity Mentions
   */
  total_entity_mentions: number
  /**
   * Total Canonical Entities
   */
  total_canonical_entities: number
  /**
   * Average Cluster Size
   */
  average_cluster_size: number
  /**
   * Resolution Requests
   */
  resolution_requests: number
}

/**
 * Statistics
 *
 * Aggregated statistics for the curation dashboard.
 */
export type Statistics = {
  registry: RegistryStatistics
  curation: CurationStatistics
}

/**
 * TokenResponse
 *
 * JWT token pair response.
 */
export type TokenResponse = {
  /**
   * Access Token
   */
  access_token: string
  /**
   * Refresh Token
   */
  refresh_token: string
  /**
   * Token Type
   */
  token_type?: string
}

/**
 * UserActionSummary
 *
 * User action summary for list display.
 */
export type UserActionSummary = {
  /**
   * Id
   */
  id: string
  about_entity_mention: EntityMentionPreview
  /**
   * Candidates
   */
  candidates: Array<ClusterReference>
  selected_cluster?: ClusterReference | null
  action_type: UserActionType
  /**
   * Actor
   */
  actor: string
  /**
   * Created At
   */
  created_at: string
  /**
   * Metadata
   */
  metadata?: unknown | null
}

/**
 * UserActionType
 *
 * Types of curator actions on entity mention resolutions
 */
export const UserActionType = {
  ACCEPT_TOP: 'ACCEPT_TOP',
  ACCEPT_ALTERNATIVE: 'ACCEPT_ALTERNATIVE',
  REJECT_ALL: 'REJECT_ALL'
} as const

/**
 * UserActionType
 *
 * Types of curator actions on entity mention resolutions
 */
export type UserActionType =
  (typeof UserActionType)[keyof typeof UserActionType]

/**
 * UserContext
 *
 * Authenticated user context carried through the request lifecycle.
 */
export type UserContext = {
  /**
   * Id
   */
  id: string
  /**
   * Email
   */
  email: string
  /**
   * Is Active
   */
  is_active: boolean
  /**
   * Is Superuser
   */
  is_superuser: boolean
  /**
   * Is Verified
   */
  is_verified: boolean
}

/**
 * UserPatchRequest
 *
 * Admin request to update user flags.
 */
export type UserPatchRequest = {
  /**
   * Is Active
   */
  is_active?: boolean | null
  /**
   * Is Superuser
   */
  is_superuser?: boolean | null
  /**
   * Is Verified
   */
  is_verified?: boolean | null
}

/**
 * UserResponse
 *
 * Public user representation (no password).
 */
export type UserResponse = {
  /**
   * Id
   */
  id: string
  /**
   * Email
   */
  email: string
  /**
   * Is Active
   */
  is_active: boolean
  /**
   * Is Superuser
   */
  is_superuser: boolean
  /**
   * Is Verified
   */
  is_verified: boolean
  /**
   * Created At
   */
  created_at: string
  /**
   * Updated At
   */
  updated_at?: string | null
}

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>
  /**
   * Message
   */
  msg: string
  /**
   * Error Type
   */
  type: string
  /**
   * Input
   */
  input?: unknown
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown
  }
}

export type HealthHealthGetData = {
  body?: never
  path?: never
  query?: never
  url: '/health'
}

export type HealthHealthGetResponses = {
  /**
   * Response Health Health Get
   *
   * Successful Response
   */
  200: {
    [key: string]: string
  }
}

export type HealthHealthGetResponse =
  HealthHealthGetResponses[keyof HealthHealthGetResponses]

export type RegisterApiV1AuthRegisterPostData = {
  body: RegisterRequest
  path?: never
  query?: never
  url: '/api/v1/auth/register'
}

export type RegisterApiV1AuthRegisterPostErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse
  /**
   * Conflict
   */
  409: ErrorResponse
}

export type RegisterApiV1AuthRegisterPostError =
  RegisterApiV1AuthRegisterPostErrors[keyof RegisterApiV1AuthRegisterPostErrors]

export type RegisterApiV1AuthRegisterPostResponses = {
  /**
   * Successful Response
   */
  201: UserResponse
}

export type RegisterApiV1AuthRegisterPostResponse =
  RegisterApiV1AuthRegisterPostResponses[keyof RegisterApiV1AuthRegisterPostResponses]

export type LoginApiV1AuthLoginPostData = {
  body: LoginRequest
  path?: never
  query?: never
  url: '/api/v1/auth/login'
}

export type LoginApiV1AuthLoginPostErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse
  /**
   * Unauthorized
   */
  401: ErrorResponse
}

export type LoginApiV1AuthLoginPostError =
  LoginApiV1AuthLoginPostErrors[keyof LoginApiV1AuthLoginPostErrors]

export type LoginApiV1AuthLoginPostResponses = {
  /**
   * Successful Response
   */
  200: TokenResponse
}

export type LoginApiV1AuthLoginPostResponse =
  LoginApiV1AuthLoginPostResponses[keyof LoginApiV1AuthLoginPostResponses]

export type RefreshApiV1AuthRefreshPostData = {
  body: RefreshRequest
  path?: never
  query?: never
  url: '/api/v1/auth/refresh'
}

export type RefreshApiV1AuthRefreshPostErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse
  /**
   * Unauthorized
   */
  401: ErrorResponse
}

export type RefreshApiV1AuthRefreshPostError =
  RefreshApiV1AuthRefreshPostErrors[keyof RefreshApiV1AuthRefreshPostErrors]

export type RefreshApiV1AuthRefreshPostResponses = {
  /**
   * Successful Response
   */
  200: TokenResponse
}

export type RefreshApiV1AuthRefreshPostResponse =
  RefreshApiV1AuthRefreshPostResponses[keyof RefreshApiV1AuthRefreshPostResponses]

export type ListDecisionsApiV1CurationDecisionsGetData = {
  body?: never
  path?: never
  query?: {
    /**
     * Entity Type
     *
     * Filter by entity type
     */
    entity_type?: string | null
    /**
     * Confidence Min
     *
     * Minimum confidence
     */
    confidence_min?: number | null
    /**
     * Confidence Max
     *
     * Maximum confidence
     */
    confidence_max?: number | null
    /**
     * Similarity Min
     *
     * Minimum similarity
     */
    similarity_min?: number | null
    /**
     * Similarity Max
     *
     * Maximum similarity
     */
    similarity_max?: number | null
    /**
     * Search
     *
     * Search text
     */
    search?: string | null
    /**
     * Ordering
     *
     * Ordering field
     */
    ordering?: DecisionOrdering | null
    /**
     * Cursor
     *
     * Pagination cursor from previous response
     */
    cursor?: string | null
    /**
     * Limit
     *
     * Items per page
     */
    limit?: number
  }
  url: '/api/v1/curation/decisions'
}

export type ListDecisionsApiV1CurationDecisionsGetErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse
}

export type ListDecisionsApiV1CurationDecisionsGetError =
  ListDecisionsApiV1CurationDecisionsGetErrors[keyof ListDecisionsApiV1CurationDecisionsGetErrors]

export type ListDecisionsApiV1CurationDecisionsGetResponses = {
  /**
   * Successful Response
   */
  200: CursorPageDecisionSummary
}

export type ListDecisionsApiV1CurationDecisionsGetResponse =
  ListDecisionsApiV1CurationDecisionsGetResponses[keyof ListDecisionsApiV1CurationDecisionsGetResponses]

export type GetProposedCanonicalEntityApiV1CurationDecisionsDecisionIdProposedCanonicalEntityGetData =
  {
    body?: never
    path: {
      /**
       * Decision Id
       */
      decision_id: string
    }
    query?: never
    url: '/api/v1/curation/decisions/{decision_id}/proposed-canonical-entity'
  }

export type GetProposedCanonicalEntityApiV1CurationDecisionsDecisionIdProposedCanonicalEntityGetErrors =
  {
    /**
     * Bad Request
     */
    400: ErrorResponse
    /**
     * Not Found
     */
    404: ErrorResponse
  }

export type GetProposedCanonicalEntityApiV1CurationDecisionsDecisionIdProposedCanonicalEntityGetError =
  GetProposedCanonicalEntityApiV1CurationDecisionsDecisionIdProposedCanonicalEntityGetErrors[keyof GetProposedCanonicalEntityApiV1CurationDecisionsDecisionIdProposedCanonicalEntityGetErrors]

export type GetProposedCanonicalEntityApiV1CurationDecisionsDecisionIdProposedCanonicalEntityGetResponses =
  {
    /**
     * Successful Response
     */
    200: CanonicalEntityPreview
  }

export type GetProposedCanonicalEntityApiV1CurationDecisionsDecisionIdProposedCanonicalEntityGetResponse =
  GetProposedCanonicalEntityApiV1CurationDecisionsDecisionIdProposedCanonicalEntityGetResponses[keyof GetProposedCanonicalEntityApiV1CurationDecisionsDecisionIdProposedCanonicalEntityGetResponses]

export type GetAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGetData =
  {
    body?: never
    path: {
      /**
       * Decision Id
       */
      decision_id: string
    }
    query?: {
      /**
       * Page
       *
       * Page number
       */
      page?: number
      /**
       * Per Page
       *
       * Items per page
       */
      per_page?: number
    }
    url: '/api/v1/curation/decisions/{decision_id}/alternative-canonical-entities'
  }

export type GetAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGetErrors =
  {
    /**
     * Bad Request
     */
    400: ErrorResponse
    /**
     * Not Found
     */
    404: ErrorResponse
  }

export type GetAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGetError =
  GetAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGetErrors[keyof GetAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGetErrors]

export type GetAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGetResponses =
  {
    /**
     * Successful Response
     */
    200: PaginatedResultCanonicalEntityPreview
  }

export type GetAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGetResponse =
  GetAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGetResponses[keyof GetAlternativeCanonicalEntitiesApiV1CurationDecisionsDecisionIdAlternativeCanonicalEntitiesGetResponses]

export type AcceptDecisionApiV1CurationDecisionsDecisionIdAcceptPostData = {
  body?: never
  path: {
    /**
     * Decision Id
     */
    decision_id: string
  }
  query?: never
  url: '/api/v1/curation/decisions/{decision_id}/accept'
}

export type AcceptDecisionApiV1CurationDecisionsDecisionIdAcceptPostErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse
  /**
   * Not Found
   */
  404: ErrorResponse
  /**
   * Conflict
   */
  409: ErrorResponse
}

export type AcceptDecisionApiV1CurationDecisionsDecisionIdAcceptPostError =
  AcceptDecisionApiV1CurationDecisionsDecisionIdAcceptPostErrors[keyof AcceptDecisionApiV1CurationDecisionsDecisionIdAcceptPostErrors]

export type AcceptDecisionApiV1CurationDecisionsDecisionIdAcceptPostResponses =
  {
    /**
     * Successful Response
     */
    204: void
  }

export type AcceptDecisionApiV1CurationDecisionsDecisionIdAcceptPostResponse =
  AcceptDecisionApiV1CurationDecisionsDecisionIdAcceptPostResponses[keyof AcceptDecisionApiV1CurationDecisionsDecisionIdAcceptPostResponses]

export type RejectDecisionApiV1CurationDecisionsDecisionIdRejectPostData = {
  body?: never
  path: {
    /**
     * Decision Id
     */
    decision_id: string
  }
  query?: never
  url: '/api/v1/curation/decisions/{decision_id}/reject'
}

export type RejectDecisionApiV1CurationDecisionsDecisionIdRejectPostErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse
  /**
   * Not Found
   */
  404: ErrorResponse
  /**
   * Conflict
   */
  409: ErrorResponse
}

export type RejectDecisionApiV1CurationDecisionsDecisionIdRejectPostError =
  RejectDecisionApiV1CurationDecisionsDecisionIdRejectPostErrors[keyof RejectDecisionApiV1CurationDecisionsDecisionIdRejectPostErrors]

export type RejectDecisionApiV1CurationDecisionsDecisionIdRejectPostResponses =
  {
    /**
     * Successful Response
     */
    204: void
  }

export type RejectDecisionApiV1CurationDecisionsDecisionIdRejectPostResponse =
  RejectDecisionApiV1CurationDecisionsDecisionIdRejectPostResponses[keyof RejectDecisionApiV1CurationDecisionsDecisionIdRejectPostResponses]

export type AssignDecisionApiV1CurationDecisionsDecisionIdAssignPostData = {
  body: AssignRequest
  path: {
    /**
     * Decision Id
     */
    decision_id: string
  }
  query?: never
  url: '/api/v1/curation/decisions/{decision_id}/assign'
}

export type AssignDecisionApiV1CurationDecisionsDecisionIdAssignPostErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse
  /**
   * Not Found
   */
  404: ErrorResponse
  /**
   * Conflict
   */
  409: ErrorResponse
}

export type AssignDecisionApiV1CurationDecisionsDecisionIdAssignPostError =
  AssignDecisionApiV1CurationDecisionsDecisionIdAssignPostErrors[keyof AssignDecisionApiV1CurationDecisionsDecisionIdAssignPostErrors]

export type AssignDecisionApiV1CurationDecisionsDecisionIdAssignPostResponses =
  {
    /**
     * Successful Response
     */
    204: void
  }

export type AssignDecisionApiV1CurationDecisionsDecisionIdAssignPostResponse =
  AssignDecisionApiV1CurationDecisionsDecisionIdAssignPostResponses[keyof AssignDecisionApiV1CurationDecisionsDecisionIdAssignPostResponses]

export type BulkAcceptDecisionsApiV1CurationDecisionsBulkAcceptPostData = {
  body: BulkActionRequest
  path?: never
  query?: never
  url: '/api/v1/curation/decisions/bulk-accept'
}

export type BulkAcceptDecisionsApiV1CurationDecisionsBulkAcceptPostErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse
}

export type BulkAcceptDecisionsApiV1CurationDecisionsBulkAcceptPostError =
  BulkAcceptDecisionsApiV1CurationDecisionsBulkAcceptPostErrors[keyof BulkAcceptDecisionsApiV1CurationDecisionsBulkAcceptPostErrors]

export type BulkAcceptDecisionsApiV1CurationDecisionsBulkAcceptPostResponses = {
  /**
   * Successful Response
   */
  200: BulkActionResponse
}

export type BulkAcceptDecisionsApiV1CurationDecisionsBulkAcceptPostResponse =
  BulkAcceptDecisionsApiV1CurationDecisionsBulkAcceptPostResponses[keyof BulkAcceptDecisionsApiV1CurationDecisionsBulkAcceptPostResponses]

export type BulkRejectDecisionsApiV1CurationDecisionsBulkRejectPostData = {
  body: BulkActionRequest
  path?: never
  query?: never
  url: '/api/v1/curation/decisions/bulk-reject'
}

export type BulkRejectDecisionsApiV1CurationDecisionsBulkRejectPostErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse
}

export type BulkRejectDecisionsApiV1CurationDecisionsBulkRejectPostError =
  BulkRejectDecisionsApiV1CurationDecisionsBulkRejectPostErrors[keyof BulkRejectDecisionsApiV1CurationDecisionsBulkRejectPostErrors]

export type BulkRejectDecisionsApiV1CurationDecisionsBulkRejectPostResponses = {
  /**
   * Successful Response
   */
  200: BulkActionResponse
}

export type BulkRejectDecisionsApiV1CurationDecisionsBulkRejectPostResponse =
  BulkRejectDecisionsApiV1CurationDecisionsBulkRejectPostResponses[keyof BulkRejectDecisionsApiV1CurationDecisionsBulkRejectPostResponses]

export type GetStatisticsApiV1CurationStatsGetData = {
  body?: never
  path?: never
  query?: {
    /**
     * Entity Type
     *
     * Filter by entity type
     */
    entity_type?: string | null
    /**
     * Timeframe Start
     *
     * Start of timeframe
     */
    timeframe_start?: string | null
    /**
     * Timeframe End
     *
     * End of timeframe
     */
    timeframe_end?: string | null
  }
  url: '/api/v1/curation/stats'
}

export type GetStatisticsApiV1CurationStatsGetErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse
}

export type GetStatisticsApiV1CurationStatsGetError =
  GetStatisticsApiV1CurationStatsGetErrors[keyof GetStatisticsApiV1CurationStatsGetErrors]

export type GetStatisticsApiV1CurationStatsGetResponses = {
  /**
   * Successful Response
   */
  200: Statistics
}

export type GetStatisticsApiV1CurationStatsGetResponse =
  GetStatisticsApiV1CurationStatsGetResponses[keyof GetStatisticsApiV1CurationStatsGetResponses]

export type ListUserActionsApiV1UserActionsGetData = {
  body?: never
  path?: never
  query?: {
    /**
     * Action Type
     */
    action_type?: UserActionType | null
    /**
     * Actor
     */
    actor?: string | null
    /**
     * Time Range Start
     */
    time_range_start?: string | null
    /**
     * Time Range End
     */
    time_range_end?: string | null
    /**
     * Page
     *
     * Page number
     */
    page?: number
    /**
     * Per Page
     *
     * Items per page
     */
    per_page?: number
  }
  url: '/api/v1/user-actions'
}

export type ListUserActionsApiV1UserActionsGetErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse
  /**
   * Forbidden
   */
  403: ErrorResponse
}

export type ListUserActionsApiV1UserActionsGetError =
  ListUserActionsApiV1UserActionsGetErrors[keyof ListUserActionsApiV1UserActionsGetErrors]

export type ListUserActionsApiV1UserActionsGetResponses = {
  /**
   * Successful Response
   */
  200: PaginatedResultUserActionSummary
}

export type ListUserActionsApiV1UserActionsGetResponse =
  ListUserActionsApiV1UserActionsGetResponses[keyof ListUserActionsApiV1UserActionsGetResponses]

export type ListUsersApiV1UsersGetData = {
  body?: never
  path?: never
  query?: {
    /**
     * Page
     *
     * Page number
     */
    page?: number
    /**
     * Per Page
     *
     * Items per page
     */
    per_page?: number
  }
  url: '/api/v1/users'
}

export type ListUsersApiV1UsersGetErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse
  /**
   * Forbidden
   */
  403: ErrorResponse
}

export type ListUsersApiV1UsersGetError =
  ListUsersApiV1UsersGetErrors[keyof ListUsersApiV1UsersGetErrors]

export type ListUsersApiV1UsersGetResponses = {
  /**
   * Successful Response
   */
  200: PaginatedResultUserResponse
}

export type ListUsersApiV1UsersGetResponse =
  ListUsersApiV1UsersGetResponses[keyof ListUsersApiV1UsersGetResponses]

export type CreateUserApiV1UsersPostData = {
  body: CreateUserRequest
  path?: never
  query?: never
  url: '/api/v1/users'
}

export type CreateUserApiV1UsersPostErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse
  /**
   * Forbidden
   */
  403: ErrorResponse
  /**
   * Conflict
   */
  409: ErrorResponse
}

export type CreateUserApiV1UsersPostError =
  CreateUserApiV1UsersPostErrors[keyof CreateUserApiV1UsersPostErrors]

export type CreateUserApiV1UsersPostResponses = {
  /**
   * Successful Response
   */
  201: UserResponse
}

export type CreateUserApiV1UsersPostResponse =
  CreateUserApiV1UsersPostResponses[keyof CreateUserApiV1UsersPostResponses]

export type PatchUserApiV1UsersUserIdPatchData = {
  body: UserPatchRequest
  path: {
    /**
     * User Id
     */
    user_id: string
  }
  query?: never
  url: '/api/v1/users/{user_id}'
}

export type PatchUserApiV1UsersUserIdPatchErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse
  /**
   * Forbidden
   */
  403: ErrorResponse
  /**
   * Not Found
   */
  404: ErrorResponse
  /**
   * Conflict
   */
  409: ErrorResponse
}

export type PatchUserApiV1UsersUserIdPatchError =
  PatchUserApiV1UsersUserIdPatchErrors[keyof PatchUserApiV1UsersUserIdPatchErrors]

export type PatchUserApiV1UsersUserIdPatchResponses = {
  /**
   * Successful Response
   */
  200: UserResponse
}

export type PatchUserApiV1UsersUserIdPatchResponse =
  PatchUserApiV1UsersUserIdPatchResponses[keyof PatchUserApiV1UsersUserIdPatchResponses]

export type GetCurrentUserApiV1UsersMeGetData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/users/me'
}

export type GetCurrentUserApiV1UsersMeGetErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse
}

export type GetCurrentUserApiV1UsersMeGetError =
  GetCurrentUserApiV1UsersMeGetErrors[keyof GetCurrentUserApiV1UsersMeGetErrors]

export type GetCurrentUserApiV1UsersMeGetResponses = {
  /**
   * Successful Response
   */
  200: UserContext
}

export type GetCurrentUserApiV1UsersMeGetResponse =
  GetCurrentUserApiV1UsersMeGetResponses[keyof GetCurrentUserApiV1UsersMeGetResponses]
